// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fitnessCenter.Models;

#nullable disable

namespace fitnessCenter.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20251205204256_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyGoal", b =>
                {
                    b.Property<int>("goalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("goalId"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("goal")
                        .HasColumnType("text");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.HasKey("goalId");

                    b.HasIndex("UserId");

                    b.ToTable("dailyGoals");
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.Property<int>("exId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("exId"));

                    b.Property<string>("exerciseType")
                        .HasColumnType("text");

                    b.HasKey("exId");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("Man", b =>
                {
                    b.Property<int>("manId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("manId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("age")
                        .HasColumnType("integer");

                    b.Property<int>("boy")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("whoIam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("wight")
                        .HasColumnType("integer");

                    b.HasKey("manId");

                    b.ToTable("men");

                    b.HasDiscriminator().HasValue("Man");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("notId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("notId"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("msj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("notId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Admin", b =>
                {
                    b.HasBaseType("Man");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Cotch", b =>
                {
                    b.HasBaseType("Man");

                    b.PrimitiveCollection<List<string>>("available_times")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("cotch_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Cotch");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasBaseType("Man");

                    b.Property<int?>("CotchmanId")
                        .HasColumnType("integer");

                    b.Property<int?>("exerciseexId")
                        .HasColumnType("integer");

                    b.Property<string>("subscribeStatus")
                        .HasColumnType("text");

                    b.HasIndex("CotchmanId");

                    b.HasIndex("exerciseexId");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("DailyGoal", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("dailyGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Cotch", null)
                        .WithMany("users_that_i_train")
                        .HasForeignKey("CotchmanId");

                    b.HasOne("Exercise", "exercise")
                        .WithMany()
                        .HasForeignKey("exerciseexId");

                    b.Navigation("exercise");
                });

            modelBuilder.Entity("Cotch", b =>
                {
                    b.Navigation("users_that_i_train");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("dailyGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
