// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fitnessCenter.Models;

#nullable disable

namespace fitnessCenter.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20260124224017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DailyGoal", b =>
                {
                    b.Property<int>("goalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("goalId"));

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("goalId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("dailyGoals");
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.Property<int>("exId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("exId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("exerciseType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("exId");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("Man", b =>
                {
                    b.Property<int>("manId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("manId"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("boy")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("number")
                        .HasColumnType("bigint");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("whoIam")
                        .HasColumnType("int");

                    b.Property<int>("wight")
                        .HasColumnType("int");

                    b.HasKey("manId");

                    b.ToTable("men");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("notId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ManId")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("msj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("notId");

                    b.HasIndex("ManId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("fitnessCenter.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppointmentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CotchId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CotchId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("Admin", b =>
                {
                    b.HasBaseType("Man");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Cotch", b =>
                {
                    b.HasBaseType("Man");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("available_times")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cotch_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Cotches", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasBaseType("Man");

                    b.Property<int?>("CotchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("exerciseexId")
                        .HasColumnType("int");

                    b.Property<string>("subscribeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CotchId");

                    b.HasIndex("exerciseexId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DailyGoal", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("dailyGoal")
                        .HasForeignKey("DailyGoal", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("Man", "Man")
                        .WithMany("notifications")
                        .HasForeignKey("ManId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Man");
                });

            modelBuilder.Entity("fitnessCenter.Models.Appointment", b =>
                {
                    b.HasOne("Cotch", "Cotch")
                        .WithMany()
                        .HasForeignKey("CotchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cotch");

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Admin", b =>
                {
                    b.HasOne("Man", null)
                        .WithOne()
                        .HasForeignKey("Admin", "manId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cotch", b =>
                {
                    b.HasOne("Exercise", "Exercise")
                        .WithMany("availCotchs")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("Man", null)
                        .WithOne()
                        .HasForeignKey("Cotch", "manId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Cotch", "cotch")
                        .WithMany("users_that_i_train")
                        .HasForeignKey("CotchId");

                    b.HasOne("Exercise", "exercise")
                        .WithMany()
                        .HasForeignKey("exerciseexId");

                    b.HasOne("Man", null)
                        .WithOne()
                        .HasForeignKey("User", "manId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cotch");

                    b.Navigation("exercise");
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.Navigation("availCotchs");
                });

            modelBuilder.Entity("Man", b =>
                {
                    b.Navigation("notifications");
                });

            modelBuilder.Entity("Cotch", b =>
                {
                    b.Navigation("users_that_i_train");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("dailyGoal");
                });
#pragma warning restore 612, 618
        }
    }
}
